### PR TITLE
Refactor to allow multiple image builds

### PR DESCRIPTION
**Pull request by faeizmahrus**
## Simple refactor to generate multiple image containers using the same GitHub Workflow/Actions.
Containerfiles must be stored in /Containerfiles directory, the name of the ContainerFile for an image must be the same as the image name.

e.g. to generate an image named `debian-test-dbn`, the relevent ContainerFile should be /Containerfiles/debian-test-dbn
Also added an extra /packages directory for packagelists and other things to be stored inside of.

### CODE REVIEW

**Comment by faeizmahrus** [comment]
I still find it kinda hacky, is there anyway to scan the Containerfiles directory for containerfiles and add those as arguments for matrix.containerfile ?

This way the user won't need to manually add the names for their containerfile to the .yml workflow file each time they want to add another distrobox container.

**Comment by m2Giles** [comment]
This looks fine. I would put a guard on fedora-sample so it's not being pushed. In fact I'm unsure if that sample should even be on here right now.

I do like this extension for those who want to fork this repo.

**Comment by castrojo** [comment]
Yeah I'm not sure we want/need the fedora sample?

**Comment by faeizmahrus** [comment]
> Yeah I'm not sure we want/need the fedora sample? I think we should just keep the one we have so we don't have to maintain a matrix of boxes like we do for the toolboxes repo.

It was included as an example, for demonstration purposes.

I can comment out the fedora-sample line in `build-boxkit.yml` file so it doesn't actually build, and add a comment saying -
"Uncommenting this line will also build the fedora-sample image"

I think fedora-sample should be renamed to fedora-example, to further clarify it's purpose.

**Comment by faeizmahrus** [comment]
I did some misc. changes, primarily enabling OCI image generation by setting `oci: true` in the builder action, and removing the obselete `--disable-content-trust` argument from Push to GHCR action.

I also added `workflow_dispatch:` so users can manually trigger builds.

Let me know if any of the changes need to be reverted.

**Pull request merged**
